export const reviews = [
  {
    id: 1,
    customer: "Priya Sharma",
    product: "Tomato",
    date: "02 Jul 2026",
    rating: 5,
    review:
      "Excellent quality tomatoes! Very fresh and juicy. Delivery was on time.",
    verified: true,
  },
  {
    id: 2,
    customer: "Ramesh Patel",
    product: "Potato",
    date: "01 Jul 2026",
    rating: 4,
    review: "Good quality potatoes. Packaging was good. Will order again.",
    verified: true,
  },
  {
    id: 3,
    customer: "Sneha Kapoor",
    product: "Onion",
    date: "30 Jun 2026",
    rating: 5,
    review: "Very fresh onions and good pricing. Highly recommended!",
    verified: true,
  },
   {
    id: 1,
    customer: "Priya Sharma",
    product: "Tomato",
    date: "02 Jul 2026",
    rating: 5,
    review:
      "Excellent quality tomatoes! Very fresh and juicy. Delivery was on time.",
    verified: true,
  },
  {
    id: 2,
    customer: "Ramesh Patel",
    product: "Potato",
    date: "01 Jul 2026",
    rating: 4,
    review: "Good quality potatoes. Packaging was good. Will order again.",
    verified: true,
  },
  {
    id: 3,
    customer: "Sneha Kapoor",
    product: "Onion",
    date: "30 Jun 2026",
    rating: 5,
    review: "Very fresh onions and good pricing. Highly recommended!",
    verified: true,
  },
   {
    id: 1,
    customer: "Priya Sharma",
    product: "Tomato",
    date: "02 Jul 2026",
    rating: 5,
    review:
      "Excellent quality tomatoes! Very fresh and juicy. Delivery was on time.",
    verified: true,
  },
  {
    id: 2,
    customer: "Ramesh Patel",
    product: "Potato",
    date: "01 Jul 2026",
    rating: 4,
    review: "Good quality potatoes. Packaging was good. Will order again.",
    verified: true,
  },
  {
    id: 3,
    customer: "Sneha Kapoor",
    product: "Onion",
    date: "30 Jun 2026",
    rating: 5,
    review: "Very fresh onions and good pricing. Highly recommended!",
    verified: true,
  },
   {
    id: 1,
    customer: "Priya Sharma",
    product: "Tomato",
    date: "02 Jul 2026",
    rating: 5,
    review:
      "Excellent quality tomatoes! Very fresh and juicy. Delivery was on time.",
    verified: true,
  },
  {
    id: 2,
    customer: "Ramesh Patel",
    product: "Potato",
    date: "01 Jul 2026",
    rating: 4,
    review: "Good quality potatoes. Packaging was good. Will order again.",
    verified: true,
  },
  {
    id: 3,
    customer: "Sneha Kapoor",
    product: "Onion",
    date: "30 Jun 2026",
    rating: 5,
    review: "Very fresh onions and good pricing. Highly recommended!",
    verified: true,
  },
   {
    id: 1,
    customer: "Priya Sharma",
    product: "Tomato",
    date: "02 Jul 2026",
    rating: 5,
    review:
      "Excellent quality tomatoes! Very fresh and juicy. Delivery was on time.",
    verified: true,
  },
  {
    id: 2,
    customer: "Ramesh Patel",
    product: "Potato",
    date: "01 Jul 2026",
    rating: 4,
    review: "Good quality potatoes. Packaging was good. Will order again.",
    verified: true,
  },
  {
    id: 3,
    customer: "Sneha Kapoor",
    product: "Onion",
    date: "30 Jun 2026",
    rating: 5,
    review: "Very fresh onions and good pricing. Highly recommended!",
    verified: true,
  },
   {
    id: 1,
    customer: "Priya Sharma",
    product: "Tomato",
    date: "02 Jul 2026",
    rating: 5,
    review:
      "Excellent quality tomatoes! Very fresh and juicy. Delivery was on time.",
    verified: true,
  },
  {
    id: 2,
    customer: "Ramesh Patel",
    product: "Potato",
    date: "01 Jul 2026",
    rating: 4,
    review: "Good quality potatoes. Packaging was good. Will order again.",
    verified: true,
  },
  {
    id: 3,
    customer: "Sneha Kapoor",
    product: "Onion",
    date: "30 Jun 2026",
    rating: 5,
    review: "Very fresh onions and good pricing. Highly recommended!",
    verified: true,
  },
   {
    id: 1,
    customer: "Priya Sharma",
    product: "Tomato",
    date: "02 Jul 2026",
    rating: 5,
    review:
      "Excellent quality tomatoes! Very fresh and juicy. Delivery was on time.",
    verified: true,
  },
  {
    id: 2,
    customer: "Ramesh Patel",
    product: "Potato",
    date: "01 Jul 2026",
    rating: 4,
    review: "Good quality potatoes. Packaging was good. Will order again.",
    verified: true,
  },
  {
    id: 3,
    customer: "Sneha Kapoor",
    product: "Onion",
    date: "30 Jun 2026",
    rating: 5,
    review: "Very fresh onions and good pricing. Highly recommended!",
    verified: true,
  },
   {
    id: 1,
    customer: "Priya Sharma",
    product: "Tomato",
    date: "02 Jul 2026",
    rating: 5,
    review:
      "Excellent quality tomatoes! Very fresh and juicy. Delivery was on time.",
    verified: true,
  },
  {
    id: 2,
    customer: "Ramesh Patel",
    product: "Potato",
    date: "01 Jul 2026",
    rating: 4,
    review: "Good quality potatoes. Packaging was good. Will order again.",
    verified: true,
  },
  {
    id: 3,
    customer: "Sneha Kapoor",
    product: "Onion",
    date: "30 Jun 2026",
    rating: 5,
    review: "Very fresh onions and good pricing. Highly recommended!",
    verified: true,
  },
];